apiVersion: v1
kind: Pod
metadata:
  name: two-container-pod
spec:
  containers:
  - name: flask-container
    image: makbanov/flask-app
    ports:
    - containerPort: 80
  - name: busybox-container
    image: busybox
    command: ['sh', '-c', 'echo Waiting for a minute && sleep 60']